### ISSUE TITLE
[Bug] Wrong Inventory Name

### ISSUE THREAD

**Issue by darksaid98** [Artillex-Studios/AxShulkers#1]
**Current behavior:** When opening a shulker through the inventory/right click, the inventory name is the one set in the locale config "Shulker Box" by default.

**Expected behavior:** When opening a shulker in Vanilla the inventory name is the shulkers item name. If the locale string is empty, the shulkers item name should be used.

**Comment by BenceX100** [comment]
Done, check out https://github.com/Artillex-Studios/AxShulkers/releases/tag/1.2.0

**Comment by darksaid98** [comment]
Awesome, thanks for the quick implementation and the resource ^_^.
