### ISSUE TITLE
Incompatibility with Towny (and potentially more protection plugins)

### ISSUE THREAD

**Issue by Folas1337** [Artillex-Studios/AxShulkers#12]
It seems that the latest introduction of the config option
```yaml
delete-invalid-items: true
```
has also introduced a little problem.

If I'm using a plugin like Towny along with AxShulkers and I leave this config option true, it'll lead to a user placing a shulker box in a town they do not have access to, for some weird reason it then messes something up with AxShulkers which leads to all items inside being deleted if you try to open it afterwards.

So to reproduce:
- Install AxShulkers
- Install Towny
- Get a shulker box, put things in it through AxShulkers plugin
- Place shulker box in a town you can not place blocks in
- Open shulker box through AxShulkers plugin and see it is now empty

I hope there is a fix for this as I like the idea behind the config option but it's currently quite a problem with other plugins 😕

**Comment by BenceX100** [comment]
For some reason towny is using high for an event priority (not sure why a protection plugin would do that), and axshulkers used normal, which caused this issue, https://github.com/Artillex-Studios/AxShulkers/releases/tag/1.9.1 should solve this issue!

**Comment by Folas1337** [comment]
I just now got to verify it, seems to be working fine. Thanks once again for the quick response <3
