### ISSUE TITLE
Dupe 

### ISSUE THREAD

**Issue by bedike16** [Artillex-Studios/AxShulkers#16]
https://cdn.discordapp.com/attachments/1267121404193804329/1296151046820724746/Screen_Recording_20241013_221755_YouTube.mp4?ex=67113e3a&is=670fecba&hm=bd5af28e68ff8f897b287137bb4b5a325315e8771f409c6967b63c2537867de0&

**Comment by BenceX100** [comment]
This is a fake video, we saw the original video, it was advertising some modified ui utils mod (it was an obsfucated jar, probably a virus)

This is also way to simple for it to work, they essentially just dropped an item and closed the shulker. That will not duplicate items.

**Comment by bedike16** [comment]
Okey, thanks for the quick reply. Sorry for the misunderstandings.
