### ISSUE TITLE
[Feature] Open other shulker and close shulkers 

### ISSUE THREAD

**Issue by darksaid98** [Artillex-Studios/AxShulkers#2]
**Open other shulkers**
**Current behavior:** When viewing a shulker, completely exit the inventory if you want to open another one.
**Requested behavior:** Allow the user to open another shulker by right-clicking, even if already viewing one.

**Close behavior**
**Extra behavior:** Right-clicking the shulker you are currently viewing closes it (and if possible fallbacks to the original inventory).

**Comment by BenceX100** [comment]
Done, check out https://github.com/Artillex-Studios/AxShulkers/releases/tag/1.2.0
