### ISSUE TITLE
[bug] dupe / item disappear

### ISSUE THREAD

**Issue by cgw2023** [Artillex-Studios/AxShulkers#5]
issue:
dispenser with shulker box which contain items can dupe item to shulker box in front of dispenser

expected behavior:
no matter shulker box in dispenser contain item or not, shulker box item should not be changed

video:
https://youtu.be/tH9H3so7hPI

folia-bundler-1.20.1-R0.1-SNAPSHOT-reobf
AxShulkers-1.2.5

**Comment by BenceX100** [comment]
Hi, I can't really replicate this, where do the items disappear? Is it when you place down the shulker or when the piston breaks it? 

Also is `enable-obsfucation` enabled in the config.yml? If yes can you try this on "false"?

**Comment by cgw2023** [comment]
> enable-obsfucation

I am asking the player for more information.

`enable-obsfucation` is disabled at all time.

**Comment by cgw2023** [comment]
player also provided 2 more video for demonstration:

https://cdn.discordapp.com/attachments/1149268906888937563/1149269046185967637/Minecraft__1.20.1_-_Multiplayer_3rd-party_Server_2023-09-02_14-09-15.mp4

https://cdn.discordapp.com/attachments/1149268906888937563/1149269057544146944/Minecraft__1.20.1_-_Multiplayer_3rd-party_Server_2023-09-01_21-14-27.mp4

**Comment by BenceX100** [comment]
Thanks for the info, i will fix this as soon as i have the time, meanwhile disabling shulker dispensing (with an external plugin) can avoid this issue

**Comment by BenceX100** [comment]
https://github.com/Artillex-Studios/AxShulkers/releases/tag/1.3.0 should fix the issue
