### ISSUE TITLE
shulker box dupe with dispenser

### ISSUE THREAD

**Issue by cgw2023** [Artillex-Studios/AxShulkers#9]
similar to #7 , instead of player put the shulker box, dispenser put shulker box on hopper is causing dupe of shulkerbox.

**Comment by BenceX100** [comment]
Can confirm, I will try to fix it, but it is a bit tricky, meanwhile the setting `disable-shulker-dispensing` to true will prevent it.

**Comment by BenceX100** [comment]
Try https://github.com/Artillex-Studios/AxShulkers/releases/download/1.5.3/AxShulkers-1.5.3.jar

**Comment by BenceX100** [comment]
Actually there is a small exception, I will fix it soon (and replace the jar)

**Comment by BenceX100** [comment]
https://github.com/Artillex-Studios/AxShulkers/releases/download/1.5.4/AxShulkers-1.5.4.jar should fix it
